<a href="https://colab.research.google.com/github/victorm0202/Curso_banxico/blob/Python-basics/06_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### The NumPy ndarray: A Multidimensional Array Object

Basado de Python for Data Analysis Wes M Chap4


One of the key features of NumPy is its N-dimensional array object, or ndarray,
which is a fast, flexible container for large datasets in Python.Arrays enable you to
perform mathematical operations on whole blocks of data using similar syntax to the
equivalent operations between scalar elements.

Numpy CheatSheet:  

https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf


http://talimi.se/p/numpy/


In [ ]:
import numpy as np  # Forma convencional de exportar numpy

In [ ]:


# Generamos un ndarry random
data = np.random.randn(2, 3)
data


array([[ 0.94024179, -0.10148237,  0.34834391],
       [ 1.03511616, -0.02102503,  0.43659932]])

An ndarray is a generic multidimensional container for homogeneous data; that is, all
of the elements must be the same type .

In [ ]:
# Atributos de un ndarray
print(data.shape)

print(data.dtype)

(2, 3)
float64


The easiest way to create an array is to use the array function. This accepts any
sequence-like object (including other arrays) and produces a new NumPy array containing
the passed data.

In [ ]:
# Array vector
a=np.array([1,2,3])

print('shape:{}'.format(a.shape))
print(a, end='\n\n\n')




shape:(3,)
[1 2 3]




In [ ]:
#Array tipo matriz
a2=np.array([(1,2,3),('a','b','c')])

print('shape:{}'.format(a2.shape))
print(a2,end='\n\n\n')


shape:(2, 3)
[['1' '2' '3']
 ['a' 'b' 'c']]




In [ ]:
# Array desde una lista
lista=[i for i in range(15)]
a3=np.array(lista)
print('shape:{}'.format(a3.shape))
print(a3,end='\n\n\n')



shape:(15,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]




In [ ]:
np.array([i for i in range(15)])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# Array lista de lista
a4=np.array([lista,lista])
print('shape:{}'.format(a4.shape))
print(a4,end='\n\n\n')



shape:(2, 15)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]




In [ ]:
# La materia prima de un np tiene que ser una estructura
np.array([0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# Array dado un shape
a5=np.array(lista).reshape(3,5)
print('shape:{}'.format(a5.shape))
print(a5,end='\n\n\n')

shape:(3, 5)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]




Otros tipos de Arrays

In [ ]:
misalto='\n\n\n'

## Array de ceros
print(np.zeros(10), end=misalto)
print(np.zeros(10).reshape(2,5), end=misalto)





[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]




In [ ]:
## Array de unos

print(np.ones(16), end=misalto)
print(np.ones(16).reshape(4,2,2), end=misalto)



[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]




In [ ]:
## Array vacio

print(np.empty(10), end=misalto)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]




In [ ]:
## Identidad

print(np.identity(5),end=misalto)



[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]




In [ ]:
## Rellenar un array

np.full((2,2),3)




array([[3, 3],
       [3, 3]])

In [ ]:
np.full(4,3)

array([3, 3, 3, 3])

In [ ]:
np.full(4,3).reshape(2,2)

array([[3, 3],
       [3, 3]])

In [ ]:
np.full((4, 3), [1, 2, 3])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
# Range

print(np.arange(1,16).reshape(3,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


### Arithmetic with NumPy Arrays

In [ ]:
data

array([[ 0.94024179, -0.10148237,  0.34834391],
       [ 1.03511616, -0.02102503,  0.43659932]])

In [ ]:
print(data+2)

[[2.94024179 1.89851763 2.34834391]
 [3.03511616 1.97897497 2.43659932]]


In [ ]:
print (data+data)

[[ 1.88048359 -0.20296474  0.69668782]
 [ 2.07023231 -0.04205007  0.87319864]]


In [ ]:
# Permite la suma de un vector a un arreglo
data1=np.arange(12).reshape(3,4)
print(data1)
data2=np.arange(3).reshape(3,1)
print(data2)
print(data1+data2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0]
 [1]
 [2]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]]


In [ ]:
data1=np.arange(12).reshape(4,3)
data2=np.arange(3).reshape(1,3)
print(data1)
print(data2)
print(data1+data2)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 1 2]]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [ ]:
print(data1.shape)
print(data2.shape)

(4, 3)
(1, 3)


In [ ]:
data1=np.arange(12).reshape(3,4)
data2=np.arange(9).reshape(3,3)
data1+data2

ValueError: operands could not be broadcast together with shapes (3,4) (3,3) 

In [ ]:
data1=np.arange(12).reshape(3,4)
data2=np.arange(12).reshape(4,3)
data1+data2

In [ ]:
data = np.arange(1,10).reshape(3,3)
print(10*data)

In [ ]:
print(data*data)

In [ ]:
print(data-0.4*data)

In [ ]:
print(1/data)

In [ ]:
print(data*data>data)

### Indexing and Slicing

* Vectores

In [ ]:
arr = np.arange(27)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [ ]:
def printt(exp, salto='\n\n'):
    print(exp,end=salto)

In [ ]:
# Indexin

printt(arr[5])
  
# Cambiar elemento

arr[5]=14

printt(arr[5])

# Slicin
printt(arr[3:7])
printt(arr[3:])
printt(arr[:8])


5

14

[ 3  4 14  6]

[ 3  4 14  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]

[ 0  1  2  3  4 14  6  7]



* Matrices

In [ ]:
arr=np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


<img src="https://www.oreilly.com/library/view/python-for-data/9781449323592/httpatomoreillycomsourceoreillyimages2172114.png" alt="drawing" align="middle" width="300"/>

In [ ]:
print(arr)
# Indexin
printt(arr[0,2])

#Slicin
printt(arr[:2,0])  # Desde- hasta NO se incluye el límite superior
printt(arr[2,:])
printt(arr[:2,1:])
printt(arr[:2,:2])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
2

[0 3]

[6 7 8]

[[1 2]
 [4 5]]

[[0 1]
 [3 4]]



#### Boolean indexin

* Selecting data from an array by boolean indexing always creates a copy of the data,
even if the returned array is unchanged.
* The Python keywords and and or do not work with boolean arrays.
Use & (and) and | (or) instead.


In [ ]:

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)


['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0.88222852  1.13273006 -1.4081923  -0.39969902]
 [-0.68232467  0.39161784 -1.87120263  0.33901992]
 [ 0.99879721 -0.67269508  0.66948716 -1.17320204]
 [-0.40056976 -1.16831921 -0.34704258  0.25998767]
 [ 0.80047981 -0.59211057 -1.15643158  0.80624499]
 [ 0.03723215 -0.90942567  2.12070499 -1.03960013]
 [-0.55781301 -1.0232534   0.74983076  0.55731113]]


In [ ]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [ ]:
~(names == 'Bob')

array([False,  True,  True, False,  True,  True,  True])

In [ ]:
data[names == 'Bob']

array([[ 0.88222852,  1.13273006, -1.4081923 , -0.39969902],
       [-0.40056976, -1.16831921, -0.34704258,  0.25998767]])

In [ ]:
data[data>1]

array([1.13273006, 2.12070499])

In [ ]:
data>1

array([[False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [ ]:
data[:,0]>0

array([ True, False,  True, False,  True,  True, False])

In [ ]:
data[data[:,0]>0]

array([[ 0.88222852,  1.13273006, -1.4081923 , -0.39969902],
       [ 0.99879721, -0.67269508,  0.66948716, -1.17320204],
       [ 0.80047981, -0.59211057, -1.15643158,  0.80624499],
       [ 0.03723215, -0.90942567,  2.12070499, -1.03960013]])

In [ ]:
data[names == 'Bob', 2:]

array([[-1.4081923 , -0.39969902],
       [-0.34704258,  0.25998767]])

In [ ]:
# To select everything but 'Bob', you can either use != or negate the condition using ~:
data[~(names == 'Bob')]

array([[-0.68232467,  0.39161784, -1.87120263,  0.33901992],
       [ 0.99879721, -0.67269508,  0.66948716, -1.17320204],
       [ 0.80047981, -0.59211057, -1.15643158,  0.80624499],
       [ 0.03723215, -0.90942567,  2.12070499, -1.03960013],
       [-0.55781301, -1.0232534 ,  0.74983076,  0.55731113]])

In [ ]:
mask = (names == 'Bob') | (names == 'Will')
data[mask]

array([[ 0.88222852,  1.13273006, -1.4081923 , -0.39969902],
       [ 0.99879721, -0.67269508,  0.66948716, -1.17320204],
       [-0.40056976, -1.16831921, -0.34704258,  0.25998767],
       [ 0.80047981, -0.59211057, -1.15643158,  0.80624499]])

In [ ]:
data[data < 0]

array([-1.4081923 , -0.39969902, -0.68232467, -1.87120263, -0.67269508,
       -1.17320204, -0.40056976, -1.16831921, -0.34704258, -0.59211057,
       -1.15643158, -0.90942567, -1.03960013, -0.55781301, -1.0232534 ])

In [ ]:
#Setting values with boolean arrays works in a common-sense way. To set all of the negative values in data to 0 we need only do:
printt(data)
data[data < 0] = 0
printt(data)

[[ 0.88222852  1.13273006 -1.4081923  -0.39969902]
 [-0.68232467  0.39161784 -1.87120263  0.33901992]
 [ 0.99879721 -0.67269508  0.66948716 -1.17320204]
 [-0.40056976 -1.16831921 -0.34704258  0.25998767]
 [ 0.80047981 -0.59211057 -1.15643158  0.80624499]
 [ 0.03723215 -0.90942567  2.12070499 -1.03960013]
 [-0.55781301 -1.0232534   0.74983076  0.55731113]]

[[0.88222852 1.13273006 0.         0.        ]
 [0.         0.39161784 0.         0.33901992]
 [0.99879721 0.         0.66948716 0.        ]
 [0.         0.         0.         0.25998767]
 [0.80047981 0.         0.         0.80624499]
 [0.03723215 0.         2.12070499 0.        ]
 [0.         0.         0.74983076 0.55731113]]



#### Fancy indexin

In [ ]:
arr=np.arange(40).reshape(8,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [ ]:
#Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays

printt(arr[[5,2,1]])

printt(arr[[-5,-2,-1]])


#Here the elements (1, 0), (5, 3), (7, 1), and (2, 2) were selected.
printt(arr[[1, 5, 7, 2], [0, 3, 1, 2]])


#which is the rectangular region formed by selecting a subset of the matrix’s rows and columns 
# Consiste en un doble select
printt(arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]])


# Keep in mind that fancy indexing, unlike slicing, always copies the data into a new array


[[25 26 27 28 29]
 [10 11 12 13 14]
 [ 5  6  7  8  9]]

[[15 16 17 18 19]
 [30 31 32 33 34]
 [35 36 37 38 39]]

[ 5 28 36 12]

[[ 5  8  6  7]
 [25 28 26 27]
 [35 38 36 37]
 [10 13 11 12]]



#### Transposing Arrays

In [ ]:
arr = np.arange(15).reshape((3, 5))
printt(arr)
printt(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]



### Universal Functions: Fast Element-Wise Array Functions

A universal function, or ufunc, is a function that performs element-wise operations
on data in ndarrays. You can think of them as fast vectorized wrappers for simple
functions that take one or more scalar values and produce one or more scalar results.


In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Raiz cuadrada por entrada
printt(np.sqrt(arr))

# Exponencial por entrada

printt(np.exp(arr).round())

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]

[1.000e+00 3.000e+00 7.000e+00 2.000e+01 5.500e+01 1.480e+02 4.030e+02
 1.097e+03 2.981e+03 8.103e+03]



<img src="https://img2018.cnblogs.com/blog/1575244/201901/1575244-20190104110528794-772383246.png" alt="drawing" align="middle" width="500"/>


<img src="https://img2018.cnblogs.com/blog/1575244/201901/1575244-20190104110534666-1972622806.png" alt="drawing" align="middle" width="500"/>



#### Mathematical and Statistical Methods

In [ ]:
arr = np.random.randn(5, 4)
arr

array([[ 0.31029012, -1.04088446, -1.08424317, -0.1394862 ],
       [ 0.82208666, -0.18018932, -0.12622644, -1.09045283],
       [-0.26347372,  0.90842893, -0.55292021, -0.86712503],
       [ 0.31888398, -0.49637914, -0.26334484,  0.21230114],
       [ 1.16174798, -0.18467769,  1.44495465, -1.02466818]])

In [ ]:
# Media global
printt(arr.mean())
printt(np.mean(arr))

-0.10676888787468716

-0.10676888787468716



In [ ]:
# Media por axis
printt(arr.mean(axis=0)) # por renglón
printt(arr.mean(axis=1)) #por columnas

[ 0.46990701 -0.19874033 -0.116356   -0.58188622]

[-0.48858093 -0.14369548 -0.19377251 -0.05713471  0.34933919]



In [ ]:
# Suma
printt(arr.sum())

printt(arr.sum(axis=0))

printt(arr.sum(axis=1))

-2.1353777574937434

[ 2.34953503 -0.99370167 -0.58178001 -2.9094311 ]

[-1.95432371 -0.57478192 -0.77509003 -0.22853886  1.39735676]



In [ ]:
arr = np.random.randn(5, 4)
print('min:',np.amin(arr))

print('min por renglon: ',np.amin(arr, axis=0))

print('max: ',np.amax(arr))

print('max por renglon: ',np.amax(arr, axis=0))

print('max por columna: ',np.amax(arr, axis=1))

print('mediana: ',np.median(arr))

print('mediana por renglon: ',np.median(arr,axis=0))

print('media pesada: ',np.average(arr))

print('media aritmética: ',np.mean(arr))

print('desviación estándar: ',np.std(arr))

print('varianza: ',np.var(arr))

print('Percentil 90: ',np.percentile(arr, 90))

print('cuantil 0.9: ',np.quantile(arr, 0.9))

print('cuantil 0.5: ',np.quantile(arr, 0.5))

print('Correlación de Pearson: ',np.corrcoef(arr))

print('Covarianza: ',np.cov(arr))

min: -2.0328030751517545
min por renglon:  [-2.03280308 -1.98215815 -1.10248062 -0.12305449]
max:  2.6106793837136197
max por renglon:  [ 0.65513101 -0.11028443  0.2132211   2.61067938]
max por columna:  [0.83732126 0.34552814 2.61067938 0.2132211  0.99235428]
mediana:  -0.334176618210573
mediana por renglon:  [-1.13031551 -0.64454395 -0.54529875  0.83732126]
media pesada:  -0.2409561901218713
media aritmética:  -0.2409561901218713
desviación estándar:  1.0647439872810398
varianza:  1.133679758451127
Percentil 90:  0.8528245589232407
cuantil 0.9:  0.8528245589232407
cuantil 0.5:  -0.334176618210573
Correlación de Pearson:  [[ 1.          0.62245196  0.73906032 -0.47952723  0.14213968]
 [ 0.62245196  1.          0.72879274  0.38469326  0.84694611]
 [ 0.73906032  0.72879274  1.         -0.0024491   0.55467973]
 [-0.47952723  0.38469326 -0.0024491   1.          0.79591669]
 [ 0.14213968  0.84694611  0.55467973  0.79591669  1.        ]]
Covarianza:  [[ 0.51652309  0.31254451  1.03245727 -0

In [ ]:
arr[4,2] = None

print(arr)
print('min:',np.amin(arr))

print('min por renglon: ',np.amin(arr, axis=0))

print('max: ',np.amax(arr))

print('max por renglon: ',np.amax(arr, axis=0))

print('max por columna: ',np.amax(arr, axis=1))

print('mediana: ',np.median(arr))

print('mediana por renglon: ',np.median(arr,axis=0))

print('media pesada: ',np.average(arr))

print('media aritmética: ',np.mean(arr))

print('desviación estándar: ',np.std(arr))

print('varianza: ',np.var(arr))

print('Percentil 90: ',np.percentile(arr, 90))

print('cuantil 0.9: ',np.quantile(arr, 0.9))

print('cuantil 0.5: ',np.quantile(arr, 0.5))

print('Correlación de Pearson: ',np.corrcoef(arr))

print('Covarianza: ',np.cov(arr))


[[ 0.58501729 -0.11028443 -0.75589806  0.83732126]
 [-1.13031551 -0.85753172 -1.10248062  0.34552814]
 [ 0.65513101 -1.98215815 -0.54529875  2.61067938]
 [-2.03280308 -0.64454395  0.2132211  -0.12305449]
 [-1.22165879 -0.55079359         nan  0.99235428]]
min: nan
min por renglon:  [-2.03280308 -1.98215815         nan -0.12305449]
max:  nan
max por renglon:  [ 0.65513101 -0.11028443         nan  2.61067938]
max por columna:  [0.83732126 0.34552814 2.61067938 0.2132211         nan]
mediana:  nan
mediana por renglon:  [-1.13031551 -0.64454395         nan  0.83732126]
media pesada:  nan
media aritmética:  nan
desviación estándar:  nan
varianza:  nan
Percentil 90:  nan
cuantil 0.9:  nan
cuantil 0.5:  nan
Correlación de Pearson:  [[ 1.          0.62245196  0.73906032 -0.47952723         nan]
 [ 0.62245196  1.          0.72879274  0.38469326         nan]
 [ 0.73906032  0.72879274  1.         -0.0024491          nan]
 [-0.47952723  0.38469326 -0.0024491   1.                 nan]
 [        nan

C:\Users\CIMAT-PRESICIONM38\Anaconda3\envs\Industria 4.0\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
C:\Users\CIMAT-PRESICIONM38\Anaconda3\envs\Industria 4.0\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median for 1 results
  r = func(a, **kwargs)
C:\Users\CIMAT-PRESICIONM38\Anaconda3\envs\Industria 4.0\lib\site-packages\numpy\lib\function_base.py:3826: RuntimeWarning: Invalid value encountered in percentile
  interpolation=interpolation)


In [ ]:
print(arr)
print('min:',np.nanmin(arr))

print('max: ',np.nanmax(arr))

print('mediana: ',np.nanmedian(arr))

print('media aritmética: ',np.nanmean(arr))

print('desviación estándar: ',np.nanstd(arr))

print('varianza: ',np.nanvar(arr))

print('Percentil 90: ',np.nanpercentile(arr, 90))

print('cuantil 0.9: ',np.nanquantile(arr, 0.9))

print('cuantil 0.5: ',np.nanquantile(arr, 0.5))




[[ 0.58501729 -0.11028443 -0.75589806  0.83732126]
 [-1.13031551 -0.85753172 -1.10248062  0.34552814]
 [ 0.65513101 -1.98215815 -0.54529875  2.61067938]
 [-2.03280308 -0.64454395  0.2132211  -0.12305449]
 [-1.22165879 -0.55079359         nan  0.99235428]]
min: -2.0328030751517545
max:  2.6106793837136197
mediana:  -0.5452987505696152
media aritmética:  -0.2535562457041034
desviación estándar:  1.0909499925045025
varianza:  1.190171886145574
Percentil 90:  0.8683278610194474
cuantil 0.9:  0.8683278610194474
cuantil 0.5:  -0.5452987505696152


#### Sort, Unique and other set logic

In [ ]:
# Ordenar
arr=np.random.randn(6)
printt(arr)
arr.sort()  # La función actúa sobre  los datos originales
printt(arr)

[-1.82279018  1.779787    1.13727492 -1.30703425  0.35329307  0.14658197]

[-1.82279018 -1.30703425  0.14658197  0.35329307  1.13727492  1.779787  ]



In [ ]:
#You can sort each one-dimensional section of values in a multidimensional array inplace 
#along an axis by passing the axis number to sort:

arr=np.random.randint(1,56,25).reshape(5,5)
printt(arr)
arr.sort(1) # ordenar por renglon
printt(arr)
arr.sort(0) ## ordenar por columna
printt(arr)

[[23 37 24 42 46]
 [27 10 36  1 44]
 [49 40 30 45 34]
 [24 21 28 54 50]
 [47 43 12 27 49]]

[[23 24 37 42 46]
 [ 1 10 27 36 44]
 [30 34 40 45 49]
 [21 24 28 50 54]
 [12 27 43 47 49]]

[[ 1 10 27 36 44]
 [12 24 28 42 46]
 [21 24 37 45 49]
 [23 27 40 47 49]
 [30 34 43 50 54]]



In [ ]:
# Valores únicos
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

### Álgebra lineal 

In [ ]:
x = np.arange(1,5).reshape(2,2)
y = np.arange(1,5).reshape(2,2)
print ("Original: ")
print(x)
#  add()is used to add matrices
print ("Addition of two matrices: ")
print (np.add(x,y))
# subtract()is used to subtract matrices
print ("Subtraction of two matrices : ")
print (np.subtract(x,y))
# divide()is used to divide matrices
print ("Matrix Division : ")
print (np.divide(x,y))
print ("Multiplication of two matrices (element-wise): ")
print (np.multiply(x,y))
print ("The product of two matrices : ")
print (np.dot(x,y))
print ("square root is : ")
print (np.sqrt(x))
print ("The summation of elements : ")
print (np.sum(y))
print ("The column wise summation  : ")
print (np.sum(y,axis=0))
print ("The row wise summation: ")
print (np.sum(y,axis=1))
# using "T" to transpose the matrix
print ("Matrix transposition : ")
print (x.T)

Original: 
[[1 2]
 [3 4]]
Addition of two matrices: 
[[2 4]
 [6 8]]
Subtraction of two matrices : 
[[0 0]
 [0 0]]
Matrix Division : 
[[1. 1.]
 [1. 1.]]
Multiplication of two matrices (element-wise): 
[[ 1  4]
 [ 9 16]]
The product of two matrices : 
[[ 7 10]
 [15 22]]
square root is : 
[[1.         1.41421356]
 [1.73205081 2.        ]]
The summation of elements : 
10
The column wise summation  : 
[4 6]
The row wise summation: 
[3 7]
Matrix transposition : 
[[1 3]
 [2 4]]


In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [ ]:
# Producto matricial variaciones
print(x.dot(y))
print(x)

[[ 28.  64.]
 [ 67. 181.]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
print(np.dot(x,y))

[[ 28.  64.]
 [ 67. 181.]]


In [ ]:
print(x@y) 

[[ 28.  64.]
 [ 67. 181.]]


In [ ]:
#numpy.linalg has a standard set of matrix decompositions and things like inverse
#and determinant.

from numpy.linalg import inv




In [ ]:
# Inversa
X = np.random.randn(3, 3)
mat = X.T.dot(X)
inv(mat)

array([[  3.5823891 ,  -5.30966364, -12.41368431],
       [ -5.30966364,  12.23140001,  25.85968701],
       [-12.41368431,  25.85968701,  57.38794201]])

In [ ]:
mat@inv(mat)

array([[ 1.00000000e+00,  8.44913337e-16, -1.00627206e-15],
       [ 1.96922743e-15,  1.00000000e+00,  8.70181436e-16],
       [-4.90101357e-17,  2.36634319e-15,  1.00000000e+00]])

<img src="http://talimi.se/wp-content/uploads/2018/01/Ska%CC%88rmavbild-2018-01-02-kl.-04.29.04.png" alt="drawing" align="middle" width="300"/>
<img src="http://talimi.se/wp-content/uploads/2018/01/Ska%CC%88rmavbild-2018-01-02-kl.-04.29.57.png" alt="drawing" align="middle" width="300"/>

## Referencias

* 100 ejercicios con Numpy

  https://github.com/rougier/numpy-100